name: Test

on:
  pull_request:
    paths-ignore:
    - 'client/src/posts/**'

jobs:
  test:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: foo
        run: ls -l

      - name: install
        run: cd ./server && yarn install

      - name: test
        run: cd ./server && yarn test          
